# Generated by Django 5.1 on 2024-08-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_article_comments_alter_article_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reading_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
