# Generated by Django 5.1 on 2024-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_comment_data_comment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uthor', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('reading_time', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.ManyToManyField(blank=True, to='api.comment')),
            ],
        ),
    ]
