# Generated by Django 5.1 on 2024-08-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_comment_avatar_comment_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='uthor',
            new_name='author',
        ),
    ]
