# Generated by Django 5.1 on 2024-08-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_uthor_chat_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.ManyToManyField(blank=True, to='api.comment')),
            ],
        ),
    ]
