# Generated by Django 5.1 on 2024-09-12 03:42

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_article_content_alter_chat_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
