# Generated by Django 5.1 on 2024-09-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_tag_taggedwhatever_alter_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('avatar', models.URLField(blank=True, default='', verbose_name='Avatar')),
            ],
        ),
    ]
