# Generated by Django 5.1 on 2024-09-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_friend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id']},
        ),
    ]
